### ISSUE TITLE
LuckyPandas not showing up on the build page

### ISSUE THREAD

**Issue by J3fftw1** [TheBusyBiscuit/builds#150]
## :round_pushpin: Description (REQUIRED)

Luckypandas isnt showing up on the builds page for some reason

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Open your preferred web browser (Google Chome, Microsoft Edge, Mozilla Firefox or any other Web Browser)
2. Go to the URL https://thebusybiscuit.github.io/builds/
3. Search for j3fftw1
4. Then you will see there is no LuckyPandas

## :bulb: Expected behavior (REQUIRED)

When going to the builds page i expect LuckyPandas to show with multiple builds.

**Comment by TheBusyBiscuit** [comment]
Turns out that commit 87c5a1c88a7ddd653f8efcb779c10d1fd6d3844b was pushed by the builds program the exact same time that pull request #145 was merged, making it override the PR :LUL:
Never happened before, but just make a new PR and it will make it this time
